[package]
name = "example"
version = "0.0.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
publish = false

build = "build.rs"

[dependencies]
verilated = "0.1.2"
verilated-module = "0.1.1"

[build-dependencies]
verilator = "0.1.5"
